FROM maven:3.5.4-jdk-8-slim

RUN useradd -ms /bin/bash maven
RUN adduser maven root
RUN apt-get update
RUN apt-get install -y git
RUN apt-get install wget

WORKDIR /usr/maven
RUN wget http://mirror.metrocast.net/apache/tomcat/tomcat-8/v8.5.34/bin/apache-tomcat-8.5.34.tar.gz
RUN tar xvf apache-tomcat-8.5.34.tar.gz
RUN rm apache-tomcat-8.5.34.tar.gz

RUN git clone https://github.com/drtran/bdd-masterclass

RUN cd bdd-masterclass/automation \
	&& mvn clean install 

RUN cd bdd-masterclass/serenity \
	&& mvn clean compile 

RUN rm -Rf bdd-masterclass

EXPOSE 8080
